version: '3'

services:
  db:
    container_name: HealthIn-db
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    volumes:
      - HealthIn_data:/var/lib/mysql
#    networks:
#      - app-tier
    tty: true

#  backend:
#    container_name: HealthIn-backend
#    build:
#      context: ./
#    command: gradle bootRun
#    ports:
#      - "8080:8080"
#    networks:
#      - app-tier
#    depends_on:
#      - db
#    restart: on-failure
#    tty: true
#
#networks:
#  app-tier:
#    driver: bridge

volumes:
  HealthIn_data: null